### ISSUE TITLE
mistune 2.0.4 doesn't work in IronPython 2.7

### ISSUE THREAD

**Issue by De4dVo1ce** [lepture/mistune#326]
Hello,
I'm trying to use `mistune` in a python script that runs in IronPython 2.7.
When I try to run it, I get this error:
````
\mistune\scanner.py", line 3, in <module> 
AttributeError: 'module' object has no attribute 'Scanner'
````
Somehow, it cannot find `re.Scanner`.

I have to put the source code of the library right next to the script, because in the end, the script will be running on a server with IronPython where it is not possible to install additional packages.

**Comment by lepture** [comment]
There is no claim that mistune support IronPython
