### ISSUE TITLE
Traceback: 'DocPageRenderer' object has no attribute 'rstrip

### ISSUE THREAD

**Issue by oberstet** [lepture/mistune#17]
I am getting a traceback with 0.3.1 (which works with 0.3.0):

```
Traceback (most recent call last):
  File "website/crossbario/__init__.py", line 191, in <module>
    pages = DocPages('../crossbar.wiki')
  File "website/crossbario/__init__.py", line 153, in __init__
    self._renderer = mistune.Markdown(renderer = rend, inline = inline)
  File "mistune.py", line 899, in mistune.Markdown.__init__ (mistune.c:16104)
    inline = inline(renderer, **kwargs)
  File "mistune.py", line 502, in mistune.InlineLexer.__call__ (mistune.c:8497)
    return self.output(src)
  File "mistune.py", line 510, in mistune.InlineLexer.output (mistune.c:9059)
    src = src.rstrip('\n')
AttributeError: 'DocPageRenderer' object has no attribute 'rstrip'
make: *** [test] Error 1
```
